// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllCards() {
  return window['go']['main']['App']['AllCards']();
}

export function AllSets() {
  return window['go']['main']['App']['AllSets']();
}
