// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AllCards():Promise<Array<models.Card>>;

export function AllCardsSet(arg1:string):Promise<Array<models.Card>>;

export function AllSets():Promise<Array<models.Set>>;
